"""Sync app_users

Revision ID: 08a16d1bb71c
Revises: 6205d4c6fa57
Create Date: 2026-04-04 23:12:29.868939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08a16d1bb71c'
down_revision: Union[str, Sequence[str], None] = '6205d4c6fa57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('app_users', 'clerk_user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('app_users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('app_users', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('app_users', 'avatar_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('app_users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('app_users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('app_users_clerk_user_id_key'), 'app_users', type_='unique')
    op.create_index(op.f('ix_app_users_clerk_user_id'), 'app_users', ['clerk_user_id'], unique=True)
    op.drop_constraint(op.f('documents_user_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'app_users', ['user_id'], ['clerk_user_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('glossary_terms_user_id_fkey'), 'glossary_terms', type_='foreignkey')
    op.create_foreign_key(None, 'glossary_terms', 'app_users', ['user_id'], ['clerk_user_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('segments_user_id_fkey'), 'segments', type_='foreignkey')
    op.create_foreign_key(None, 'segments', 'app_users', ['user_id'], ['clerk_user_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('translation_memory_user_id_fkey'), 'translation_memory', type_='foreignkey')
    op.create_foreign_key(None, 'translation_memory', 'app_users', ['user_id'], ['clerk_user_id'], ondelete='CASCADE')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'translation_memory', type_='foreignkey')
    op.create_foreign_key(op.f('translation_memory_user_id_fkey'), 'translation_memory', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'segments', type_='foreignkey')
    op.create_foreign_key(op.f('segments_user_id_fkey'), 'segments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'glossary_terms', type_='foreignkey')
    op.create_foreign_key(op.f('glossary_terms_user_id_fkey'), 'glossary_terms', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_user_id_fkey'), 'documents', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_app_users_clerk_user_id'), table_name='app_users')
    op.create_unique_constraint(op.f('app_users_clerk_user_id_key'), 'app_users', ['clerk_user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('app_users', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('app_users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('app_users', 'avatar_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('app_users', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('app_users', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('app_users', 'clerk_user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_table('users',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###
