"""Initial migration

Revision ID: 6205d4c6fa57
Revises: 
Create Date: 2026-04-04 22:47:09.887686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '6205d4c6fa57'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('firebase_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('blocks', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_filename'), 'documents', ['filename'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.create_table('glossary_terms',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_glossary_terms_id'), 'glossary_terms', ['id'], unique=False)
    op.create_index(op.f('ix_glossary_terms_language'), 'glossary_terms', ['language'], unique=False)
    op.create_index(op.f('ix_glossary_terms_user_id'), 'glossary_terms', ['user_id'], unique=False)
    op.create_table('segments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=True),
    sa.Column('correction', sa.Text(), nullable=True),
    sa.Column('final_text', sa.Text(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('block_type', sa.String(), nullable=True),
    sa.Column('position', sa.JSON(), nullable=True),
    sa.Column('format_snapshot', sa.JSON(), nullable=True),
    sa.Column('tm_match_type', sa.String(), nullable=True),
    sa.Column('tm_score', sa.Float(), nullable=True),
    sa.Column('row', sa.Integer(), nullable=True),
    sa.Column('col', sa.Integer(), nullable=True),
    sa.Column('table_index', sa.Integer(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('col_count', sa.Integer(), nullable=True),
    sa.Column('col_widths', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_segments_document_id'), 'segments', ['document_id'], unique=False)
    op.create_index(op.f('ix_segments_id'), 'segments', ['id'], unique=False)
    op.create_index(op.f('ix_segments_user_id'), 'segments', ['user_id'], unique=False)
    op.create_table('translation_memory',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('document_id', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('target_text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translation_memory_document_id'), 'translation_memory', ['document_id'], unique=False)
    op.create_index(op.f('ix_translation_memory_id'), 'translation_memory', ['id'], unique=False)
    op.create_index(op.f('ix_translation_memory_language'), 'translation_memory', ['language'], unique=False)
    op.create_index(op.f('ix_translation_memory_user_id'), 'translation_memory', ['user_id'], unique=False)
    op.drop_table('document_shares')
    op.drop_table('app_users')
    op.drop_table('document_share_access')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_share_access',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('share_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('owner_clerk_user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('recipient_clerk_user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('recipient_email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('recipient_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('accessed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('document_share_access_pkey'))
    )
    op.create_table('app_users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('clerk_user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('avatar_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('app_users_pkey')),
    sa.UniqueConstraint('clerk_user_id', name=op.f('app_users_clerk_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('document_shares',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('share_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('owner_clerk_user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('access_mode', sa.TEXT(), server_default=sa.text("'viewer'::text"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('document_shares_pkey')),
    sa.UniqueConstraint('share_id', name=op.f('document_shares_share_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_index(op.f('ix_translation_memory_user_id'), table_name='translation_memory')
    op.drop_index(op.f('ix_translation_memory_language'), table_name='translation_memory')
    op.drop_index(op.f('ix_translation_memory_id'), table_name='translation_memory')
    op.drop_index(op.f('ix_translation_memory_document_id'), table_name='translation_memory')
    op.drop_table('translation_memory')
    op.drop_index(op.f('ix_segments_user_id'), table_name='segments')
    op.drop_index(op.f('ix_segments_id'), table_name='segments')
    op.drop_index(op.f('ix_segments_document_id'), table_name='segments')
    op.drop_table('segments')
    op.drop_index(op.f('ix_glossary_terms_user_id'), table_name='glossary_terms')
    op.drop_index(op.f('ix_glossary_terms_language'), table_name='glossary_terms')
    op.drop_index(op.f('ix_glossary_terms_id'), table_name='glossary_terms')
    op.drop_table('glossary_terms')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_filename'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
